bsc:
  testnet:
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545'
    chainId: 97
    gaslessRelayerContractAddress: ''
  mainnet:
    rpcUrl: 'https://bsc-dataseed.binance.org'
    chainId: 56
    gaslessRelayerContractAddress: ''
