name: CI & CD - Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build App
        run: npm run build:ci
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy:
    if: |
      always() && 
      needs.build.result == 'success' &&
      github.ref == 'refs/heads/main'

    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    needs: [build]

    steps:
      - name: Deploy Prediction API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP_PROD }}
          key: ${{ secrets.SERVER_SSH_KEY_PROD }}
          username: ${{ secrets.SERVER_SSH_USERNAME_PROD }}
          command_timeout: '30m'

          script: |
            cd /var/www/api.predchain.com
            sudo git add .
            sudo git reset --hard origin/main
            sudo git checkout main 
            sudo git pull origin main
            yarn
            yarn migrate:run
            yarn pm2:deploy:prod && yarn pm2:deploy:prod:cron
