name: Continuous Integration

on:
  pull_request:

jobs:
  lint-audit-build:
    name: Lint, Audit & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Run Linting
        run: yarn lint

      - name: Audit for vulnerabilities
        run: yarn audit-ci

      - name: Build App
        run: yarn build

  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   needs: [lint-audit-build]

  #   services:
  #     redis:
  #       image: redis
  #       # Set health checks to wait until redis has started
  #       options: >-
  #         --health-cmd "redis-cli ping"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         # Maps port 6379 on service container to the host
  #         - 6379:6379
  #     postgres:
  #       image: postgres:13.4
  #       env:
  #         POSTGRES_DB: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_PORT: 5432
  #         POSTGRES_USER: postgres
  #       ports:
  #         - 5432:5432
  #       # Set health checks to wait until postgres has started
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Use Node.js 18.17.0
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.17.0

  #     - name: Install Dependencies
  #       run: yarn install

  #     - name: Run migration
  #       env:
  #         REDIS_HOST: localhost
  #         REDIS_PORT: 6379
  #         POSTGRES_HOST: localhost
  #         POSTGRES_PORT: 5432
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: postgres
  #         POSTGRES_DB_TEST: postgres

  #       run: yarn test:migration:run

  #     - name: Run tests
  #       env:
  #         REDIS_HOST: localhost
  #         REDIS_PORT: 6379
  #         POSTGRES_HOST: localhost
  #         POSTGRES_PORT: 5432
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: postgres
  #         POSTGRES_DB_TEST: postgres
  #         NODE_OPTIONS: '--max_old_space_size=4096'

  #       run: yarn test:cov
